tournament/tournament/urls.py
# tournament/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tournament_app.urls')),  # Include tournaments app URLs
    path('accounts/', include('allauth.urls')),  # Include allauth URLs
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tournament/tournament_app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('tournaments/', TournamentsView.as_view(), name='tournaments'),
    path('tournament/<int:pk>/', TournamentDetailView.as_view(), name='tournament_detail'),
    path('tournament/create/', tournament_create, name='tournament_create'),
    path('tournament/<int:id>/edit/', tournament_edit, name='tournament_edit'),
    path('tournament/<int:tournament_id>/delete/', tournament_delete, name='tournament_delete'),
    path('tournament/<int:tournament_id>/create_team/', team_create, name='team_create'),
    path('team/<int:team_id>/create_player/', player_create, name='player_create'),
    path('team/<int:pk>/', TeamDetailView.as_view(), name='team_detail'),
    path('team/<int:team_id>/upload_video/', upload_video, name='upload_video'),
    path('player/<int:pk>/', PlayerDetailView.as_view(), name='player_detail'),
    path('update_team_score/', update_team_score, name='update_team_score'),
    path('update_team_time_score/', update_team_time_score, name='update_team_time_score'),
    path('tournament/<int:tournament_id>/toggle/', toggle_tournament_status, name='toggle_tournament_status'),

]

tournament/tournament_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

class Tournament(models.Model):
    ROUND_CHOICES = [
        (1, '1 Round'),
        (2, '2 Rounds'),
        (3, '3 Rounds'),
    ]
    TIMEZONE_CHOICES = [
        ('America/Los_Angeles', 'PST'),
        ('America/New_York', 'EST'),
        ('America/Chicago', 'CST'),
        ('America/Denver', 'MST'),
        ('UTC', 'UTC')
    ]

    GAME_MODE_CHOICES = [
        ('TimeAttack', 'Time Attack: Complete the objective in the shortest time possible.'),
        ('HighestScore', 'Highest Score: Achieve the highest score to win.'),
    ]
    
    TOURNAMENT_TYPE_CHOICES = [
        ('RoboSports', 'RoboSports: Teams design 2 robots that compete with robots of another team.'),
        ('RoboMission', 'RoboMission: Build and program a robot that solves challenges on a field.'),
        ('FutureEngineers', 'FutureEngineers: Highest Score: Achieve the highest score to win.'),
        ('FutureInnovators', 'FutureInnovators: Develop a robot project that helps solve real world problems.'),
    ]

    name = models.CharField(max_length=100)
    description = models.CharField(max_length=500, null=True)
    rules = models.CharField(max_length=500, null=True)
    date = models.DateTimeField()
    time = models.TimeField()
    image = models.ImageField(upload_to='tournament_images/', null=True, blank=True)
    location = models.CharField(max_length=255)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_tournaments')
    rounds = models.IntegerField(choices=ROUND_CHOICES, default=1, help_text="Number of rounds")
    game_mode = models.CharField(max_length=200, choices=GAME_MODE_CHOICES, default='TimeAttack')
    tournament_type = models.CharField(max_length=200, choices=TOURNAMENT_TYPE_CHOICES, default='RoboSports')
    video_url = models.URLField(max_length=500, blank=True, null=True)
    timezone = models.CharField(max_length=500, choices=TIMEZONE_CHOICES, default='UTC')
    closed = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class Players(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    age = models.IntegerField()
    emergency_contact_first_name = models.CharField(max_length=100)
    emergency_contact_last_name = models.CharField(max_length=100)
    emergency_contact_phone_number = models.CharField(max_length=15)
    address = models.CharField(max_length=100, null=True)
    country = models.CharField(max_length=100)
    state_province = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=10)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Team(models.Model):
    name = models.CharField(max_length=100)
    tournament = models.ManyToManyField(Tournament, related_name='teams')
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_teams')
    members = models.ManyToManyField(Players, related_name='teams')
    score_one = models.IntegerField(null=True, blank=True)
    score_one_edited = models.BooleanField(default=False)  # Add this field
    score_two = models.IntegerField(null=True, blank=True)
    score_two_edited = models.BooleanField(default=False)  # Add this field
    score_three = models.IntegerField(null=True, blank=True)
    score_three_edited = models.BooleanField(default=False)  # Add this field
    total_score = models.IntegerField(null=True, blank=True)
    time_score_one = models.DurationField(null=True, blank=True)
    time_score_one_edited = models.BooleanField(default=False)  # Add this field
    time_score_two = models.DurationField(null=True, blank=True)
    time_score_two_edited = models.BooleanField(default=False)  # Add this field
    time_score_three = models.DurationField(null=True, blank=True)
    time_score_three_edited = models.BooleanField(default=False)  # Add this field
    time_total_score = models.DurationField(null=True, blank=True)
    video_url = models.URLField(max_length=250, blank=True, null=True)
    coach_email = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.name


class Bracket(models.Model):
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE, related_name='brackets')
    team = models.ManyToManyField(Team, related_name='brackets')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    state = models.JSONField(default=dict)
    def __str__(self):
        return f"Bracket for {self.tournament.name}"

tournament/tournament_app/forms.py
from django import forms
from .models import *
from pytz import all_timezones

class TournamentForm(forms.ModelForm):

    class Meta:
        model = Tournament
        fields = [
            'name', 'description', 'rules', 'date', 'time', 'location',
            'rounds', 'game_mode', 'tournament_type', 'image', 'video_url', 'timezone'
        ]
        widgets = {
            'date': forms.DateInput(format='%m/%d/%Y', attrs={'type': 'text', 'placeholder': 'MM/DD/YYYY', 'class': 'form-control'}),
            'time': forms.TimeInput(format='%H:%M', attrs={'type': 'time', 'class': 'form-control'}),
            'rounds': forms.RadioSelect,
            'game_mode': forms.RadioSelect,
            'tournament_type': forms.RadioSelect, 
            'timezone': forms.Select(attrs={'class': 'form-control'}),

        }
        
class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ['name', 'coach_email']

class PlayerForm(forms.ModelForm):
    class Meta:
        model = Players
        fields = [
            'first_name', 'last_name', 'age' 
            , 'state_province', 'country'
        ]

class BracketForm(forms.ModelForm):
    class Meta:
        model = Bracket
        fields = ['tournament', 'team', 'state']

tournament/tournament_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.admin.views.decorators import staff_member_required
from django.views.generic import ListView, DetailView, TemplateView
from .models import *
from .forms import *
# from .bracket import Bracket
from django.contrib import messages
from django.http import HttpResponseForbidden, JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json 
from datetime import timedelta
from django.utils import timezone
from django.utils.dateparse import parse_duration
from operator import attrgetter
from itertools import groupby
import re

@staff_member_required
@login_required
def toggle_tournament_status(request, tournament_id):
    tournament = get_object_or_404(Tournament, id=tournament_id)
    tournament.closed = not tournament.closed  # Toggle closed status
    tournament.save()
    return redirect('tournament_detail', tournament.id)

@login_required
def tournament_delete(request, tournament_id):
    tournament = get_object_or_404(Tournament, id=tournament_id)
    if request.user != tournament.created_by:
        messages.error(request, "You do not have permission to delete this tournament.")
        return redirect('tournament_detail', tournament_id=tournament.id)
    
    if request.method == 'POST':
        tournament.delete()
        messages.success(request, "Tournament deleted successfully.")
        return redirect('tournaments')
    
    return render(request, 'tournament_confirm_delete.html', {'tournament': tournament})

def check_staff_or_superuser(user):
    return user.is_staff or user.is_superuser

@login_required
@user_passes_test(check_staff_or_superuser)
def tournament_create(request):
    if request.method == 'POST':
        form = TournamentForm(request.POST, request.FILES)
        if form.is_valid():
            tournament = form.save(commit=False)
            tournament.created_by = request.user
            tournament.save()
            messages.success(request, "Tournament successfully created!")
            return redirect('tournament_detail', pk=tournament.pk)
    else:
        form = TournamentForm()
    return render(request, 'tournament_create.html', {'form': form})

@login_required
def tournament_edit(request, id):
    tournament = get_object_or_404(Tournament, id=id)

    if request.user != tournament.created_by:
        return redirect('tournament_detail', pk=tournament.id)

    if request.method == 'POST':
        form = TournamentForm(request.POST, request.FILES, instance=tournament)
        if form.is_valid():
            form.save()
            return redirect('tournament_detail', pk=tournament.id)
    else:
        form = TournamentForm(instance=tournament)

    return render(request, 'tournament_edit.html', {
        'form': form,
        'tournament': tournament
    })

@login_required
def team_create(request, tournament_id):
    tournament = get_object_or_404(Tournament, id=tournament_id)

    if request.method == 'POST':
        form = TeamForm(request.POST)
        if form.is_valid():
            team = form.save(commit=False)
            team.created_by = request.user
            team.save()
            team.tournament.add(tournament)
            return redirect('tournament_detail', pk=tournament.id)
    else:
        form = TeamForm()

    return render(request, 'team_create.html', {'form': form, 'tournament': tournament})

YOUTUBE_URL_REGEX = (
    r'(https?://)?(www\.)?(youtube|youtu|youtube-nocookie)\.(com|be)/'
    r'(watch\?v=|embed/|v/|.+\?v=)?([^&=%\?]{11})'
)

@login_required
def upload_video(request, team_id):
    team = get_object_or_404(Team, id=team_id)
    if request.user != team.created_by:
        return HttpResponseForbidden("You are not allowed to upload a video for this team.")

    if request.method == 'POST':
        video_url = request.POST.get('video_url')
        match = re.search(YOUTUBE_URL_REGEX, video_url)
        
        if match:
            # Extract the video ID and convert it to an embeddable format
            video_id = match.group(6)
            embeddable_url = f"https://www.youtube.com/embed/{video_id}"
            team.video_url = embeddable_url
            team.save()
            return redirect('team_detail', pk=team.id)
        else:
            # If not a valid YouTube URL, handle the error (e.g., by redirecting back or displaying a message)
            return redirect('team_detail', pk=team.id)
    return redirect('team_detail', pk=team.id)

@login_required
def player_create(request, team_id):
    team = get_object_or_404(Team, id=team_id)

    if request.user != team.created_by:
        return redirect('team_detail', pk=team.id)

    if team.members.count() >= 3:
        return redirect('team_detail', pk=team.id)

    if request.method == 'POST':
        form = PlayerForm(request.POST)
        if form.is_valid():
            player = form.save(commit=False)
            player.save()
            team.members.add(player)
            return redirect('team_detail', pk=team.id)
    else:
        form = PlayerForm()

    return render(request, 'player_create.html', {'form': form, 'team': team})

@login_required
def player_detail(request, pk):
    player = get_object_or_404(Players, pk=pk)
    team = player.teams.first()
    if request.user != team.created_by:
        return redirect('team_detail', pk=team.id)
    return render(request, 'player_detail.html', {'player': player})

class IndexView(TemplateView):
    template_name = 'index.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tournaments'] = Tournament.objects.all()
        return context

class TournamentsView(ListView):
    model = Tournament
    template_name = 'tournaments.html'
    context_object_name = 'tournaments'

from django.utils.timezone import timedelta


class TournamentDetailView(DetailView):
    model = Tournament
    template_name = 'tournament_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tournament = self.get_object()
        teams = list(tournament.teams.all())  # Convert queryset to list for sorting
        user = self.request.user

        # Calculate total scores and times for each team
        for team in teams:
            team.can_edit = (user == team.created_by) or (user == tournament.created_by)
            team.total_score = (
                (team.score_one or 0) +
                (team.score_two or 0) +
                (team.score_three or 0)
            )
            team.total_time_score = (
                (team.time_score_one or timezone.timedelta(seconds=0)) +
                (team.time_score_two or timezone.timedelta(seconds=0)) +
                (team.time_score_three or timezone.timedelta(seconds=0))
            )

        # Sort and group teams based on game mode, considering ties
        if tournament.game_mode == 'HighestScore':
            teams.sort(key=attrgetter('total_score'), reverse=True)
        elif tournament.game_mode == 'TimeAttack':
            teams.sort(key=attrgetter('total_time_score'))

        # Group teams by score or time and identify top 3 rankings, including ties
        grouped_teams = []
        rank = 0
        for score_or_time, group in groupby(teams, key=attrgetter('total_score' if tournament.game_mode == 'HighestScore' else 'total_time_score')):
            group_list = list(group)
            if rank < 3:
                for team in group_list:
                    team.is_top_three = True
            grouped_teams.extend(group_list)
            rank += len(group_list)
            
        formatted_time = tournament.time.strftime("%I:%M %p") if tournament.time else None

        context['teams'] = grouped_teams
        context['round_headers'] = range(1, tournament.rounds + 1)
        context['tournament'] = tournament
        context['formatted_time'] = formatted_time  # Pass the formatted time to the context
        return context

class TeamDetailView(DetailView):
    model = Team
    template_name = 'team_detail.html'
    context_object_name = 'team'

class PlayerDetailView(DetailView):
    model = Players
    template_name = 'player_detail.html'
    context_object_name = 'player'

@csrf_exempt
@login_required
def update_team_score(request):
    if request.method == "POST":
        data = json.loads(request.body)
        team_id = data.get("team_id")
        score_field = data.get("score_field")
        score_value = data.get("score_value")
        
        try:
            team = Team.objects.get(id=team_id)
            tournament = team.tournament.first()  # Assuming a team belongs to only one tournament
            
            if request.user == tournament.created_by or (request.user == team.created_by and not getattr(team, f"{score_field}_edited")):
                setattr(team, score_field, score_value)
                if request.user != tournament.created_by:
                    setattr(team, f"{score_field}_edited", True)
                team.save()
                return JsonResponse({"success": True})
            else:
                return JsonResponse({"success": False, "error": "Permission denied"})
        except Team.DoesNotExist:
            return JsonResponse({"success": False, "error": "Team not found"})
        except Exception as e:
            return JsonResponse({"success": False, "error": str(e)})
    
    return JsonResponse({"success": False, "error": "Invalid request"})

@csrf_exempt
@login_required
def update_team_time_score(request):
    if request.method == "POST":
        data = json.loads(request.body)
        team_id = data.get("team_id")
        time_score_field = data.get("time_score_field")
        time_score_value = data.get("time_score_value")

        try:
            team = Team.objects.get(id=team_id)

tournament/tournament_app/templates/base_generic.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Tournaments App{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'tournament_app/css/basegeneric.css' %}">
    <link rel="stylesheet" href="{% static 'tournament_app/css/index.css' %}">
    <link rel="stylesheet" href="{% static 'tournament_app/css/tournaments.css' %}">
    <link rel="stylesheet" href="{% static 'tournament_app/css/tournamentID.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.0/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-scroll fixed-top shadow-0 border-bottom border-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'index' %}">
            <img src="{% static 'tournament_app/images/uselIcon.png' %}" alt="USEL Logo">
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto">
              <li class="nav-item">
                <a class="nav-link text-white" href="https://www.uselyouthrobotics.com/">USEL Website</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'account_logout' %}">Logout, {{ user.username }}</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'account_login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'account_signup' %}">Sign Up</a>
              </li>
              {% endif %}
              <li class="nav-item">
                <a class="btn btn-warning ms-3 nav-link text-white" href="{% url 'tournaments' %}">Tournaments</a>
              </li>
            </ul>
          </div>
        </div>
    </nav>
    <br>
    <div class="container mt-5 content">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="footer">
        <div class="container text-center">
            <p class="m-0">USENGINEERINGLEAGUE &copy; 2024</p>
        </div>
    </footer>

    <!-- Bootstrap JavaScript Bundle -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
</body>
</html>

tournament/tournament_app/templates/bracket_create.html
{% extends 'base_generic.html' %}

{% block title %}Create Bracket{% endblock %}

{% block content %}
<button onclick="history.back()" class="btn btn-secondary">Back</button>

<div class="container mt-5">
    <h2>Create a New Bracket for {{ tournament.name }}</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <button type="submit" name="shuffle" class="btn btn-primary">Shuffle Teams</button>
        </div>
        <div class="form-group">
            <label for="round">Round Number:</label>
            <input type="number" id="round" name="round" class="form-control" min="2" max="{{ bracket.numRounds }}">
        </div>
        <div class="form-group">
            <label for="teams">Winning Teams (comma separated):</label>
            <input type="text" id="teams" name="teams" class="form-control">
        </div>
        <div class="form-group">
            <button type="submit" name="update" class="btn btn-primary">Update Bracket</button>
        </div>
    </form>
    <pre>{{ bracket.show|safe }}</pre>
</div>
{% endblock %}

tournament/tournament_app/templates/tournaments.html
{% extends "base_generic.html" %}
{% load static %}
{% block title %}Tournaments{% endblock %}
{% load custom_filters %}
{% block content %}

<div id="svg-background-wrapper">
    <svg id="svg-background" class="position-absolute" viewBox="0 0 1920 880">
        <g>
          <linearGradient id="svg-gradient" x1="0" x2="1" y1="0" y2="0">
            <stop stop-color="hsl(217, 88%, 33.7%)" offset="0"></stop>
            <stop stop-color="hsl(217, 88%, 75.1%)" offset="1"></stop>
          </linearGradient>
          <path d="" fill="url(#svg-gradient)" opacity="0.4">
            <animate
                     attributeName="d"
                     dur="33s"
                     repeatCount="indefinite"
                     values="M0 0L 0 804.2328934685746Q 320 597.3613372284876  640 571.0708916590191T 1280 512.0661063245175T 1920 301.8788007488083L 1920 0 Z;M0 0L 0 877.6839081951588Q 320 668.0720922803877  640 649.0018928349388T 1280 328.7087077664202T 1920 162.95038242563396L 1920 0 Z;M0 0L 0 724.9886210051687Q 320 661.4364572061575  640 623.2173947479624T 1280 359.20353038907734T 1920 135.51673041732283L 1920 0 Z;M0 0L 0 804.2328934685746Q 320 597.3613372284876  640 571.0708916590191T 1280 512.0661063245175T 1920 301.8788007488083L 1920 0 Z"
                     ></animate>
          </path>
          <path d="" fill="url(#svg-gradient)" opacity="0.4">
            <animate
                     attributeName="d"
                     dur="33s"
                     repeatCount="indefinite"
                     values="M0 0L 0 765.7607191473613Q 320 641.7853945676919  640 624.2534689988059T 1280 365.27264408032966T 1920 190.38947978522663L 1920 0 Z;M0 0L 0 842.1984196370487Q 320 570.6690721707517  640 540.6844954979398T 1280 439.92879442880593T 1920 200.29713960445451L 1920 0 Z;M0 0L 0 796.6802345094818Q 320 721.9216894353016  640 696.8815669355181T 1280 373.6367381440213T 1920 196.63169821789495L 1920 0 Z;M0 0L 0 765.7607191473613Q 320 641.7853945676919  640 624.2534689988059T 1280 365.27264408032966T 1920 190.38947978522663L 1920 0 Z"
                     ></animate>
          </path>
          <path d="" fill="url(#svg-gradient)" opacity="0.4">
            <animate
                     attributeName="d"
                     dur="33s"
                     repeatCount="indefinite"
                     values="M0 0L 0 801.7562714943509Q 320 634.0247183381232  640 605.7090791951217T 1280 503.9393370140325T 1920 224.7551247480177L 1920 0 Z;M0 0L 0 821.0401780336218Q 320 670.8690783540507  640 637.0744123031742T 1280 456.40745286432224T 1920 278.1294357804296L 1920 0 Z;M0 0L 0 744.0534225112256Q 320 637.6425395409125  640 593.2079605185819T 1280 457.03995196824286T 1920 254.87693899994804L 1920 0 Z;M0 0L 0 801.7562714943509Q 320 634.0247183381232  640 605.7090791951217T 1280 503.9393370140325T 1920 224.7551247480177L 1920 0 Z"
                     ></animate>
          </path>
        
        </g>
      </svg>
</div>
<div class="d-flex justify-content-between align-items-center mb-3">
    <h1 class="mt-4 mb-3">Tournaments</h1>
    {% if user.is_staff or user.is_superuser %}
    <div class="text-right">
        <a href="{% url 'tournament_create' %}" class="btn btn-success">Create Tournament</a>
    </div>
    {% endif %}
</div>
<div class="container mt-4">
    <div class="row">
        <div class="col-md-12 mb-3">
            <div class="d-flex flex-column">
                <div class="form-inline mb-3">
                    <label for="sort" class="mr-2">Sort by:</label>
                    <select id="sort" class="form-control" onchange="sortTournaments()">
                        <option value="date">Tournament Date</option>
                        <option value="name">Tournament Name (A-Z)</option>
                        <option value="host">Host Name (A-Z)</option>
                        <option value="gamemode">Game Mode Type</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="form-inline-search">
    <input type="text" id="search" class="form-control" placeholder="Search Tournaments..." onkeyup="searchTournaments()">
</div><div class="row" id="tournament-container">
    {% for tournament in tournaments %}
    <div class="col-md-4 mb-4 tournament-card" data-name="{{ tournament.name }}" data-date="{{ tournament.date }}" data-host="{{ tournament.created_by }}">
        <div class="card">
            {% if tournament.image %}
                <img src="{{ tournament.image.url }}" class="card-img-top" alt="{{ tournament.name }}">
            {% else %}
                <img src="{% static 'tournament_app/images/usel.png' %}" class="card-img-top" alt="No Image Available">
            {% endif %}
            <div class="card-body">
                <!-- Tournament Name with Lock/Unlock Icon -->
                <h5 class="card-title">
                    {{ tournament.name }}
                    {% if tournament.closed %}
                        <i class="fas fa-lock text-danger" title="Tournament Closed"></i>
                    {% else %}
                        <i class="fas fa-unlock text-success" title="Tournament Open"></i>
                    {% endif %}
                </h5>
                
                <p class="card-text"><strong>Tournament Host: </strong> {{ tournament.created_by }}</p>
                <p><strong>Date:</strong> {{ tournament.date|date:"m/d/Y" }}</p>
                <p><strong>Time:</strong> {{ tournament.time }} {{ tournament.get_timezone_display }}</p>
                <p class="card-text"><strong>Location:</strong> {{ tournament.location }}</p>
                
                {% if tournament.game_mode %}
                    <p class="card-text"><strong>Game Mode:</strong> {{ tournament.game_mode }}</p>
                {% endif %}
                
                <a href="{% url 'tournament_detail' tournament.id %}" class="btn btn-primary">View Details</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<script>
    function sortTournaments() {
        const container = document.getElementById('tournament-container');
        const cards = Array.from(container.getElementsByClassName('tournament-card'));
        const sortBy = document.getElementById('sort').value;

        cards.sort((a, b) => {
            let aValue, bValue;
            if (sortBy === 'date') {
                aValue = new Date(a.getAttribute('data-date'));
                bValue = new Date(b.getAttribute('data-date'));
            } else if (sortBy === 'name') {
                aValue = a.getAttribute('data-name').toLowerCase();
                bValue = b.getAttribute('data-name').toLowerCase();
            } else if (sortBy === 'host') {
                aValue = a.getAttribute('data-host').toLowerCase();
                bValue = b.getAttribute('data-host').toLowerCase();
            } else if (sortBy === 'gamemode') {
                aValue = a.getAttribute('data-gamemode').toLowerCase();
                bValue = b.getAttribute('data-gamemode').toLowerCase();
            }

            if (aValue < bValue) return -1;
            if (aValue > bValue) return 1;
            return 0;
        });

        cards.forEach(card => container.appendChild(card));
    }

    function searchTournaments() {
        const searchInput = document.getElementById('search').value.toLowerCase();
        const cards = document.querySelectorAll('.tournament-card');

        cards.forEach(card => {
            const name = card.getAttribute('data-name').toLowerCase();
            if (name.includes(searchInput)) {
                card.style.display = 'block';
            } else {
                card.style.display = 'none';
            }
        });
    }
</script>
{% endblock %}